-- EXAMPLE
CREATE TABLE CUSTOMERS 
(
    CustomerID  nvarchar(64) NOT NULL,
    ContactName nvarchar(64) NOT NULL, 
    Phone nvarchar(64) NOT NULL
)

INSERT INTO CUSTOMERS (CustomerID, ContactName, Phone) VALUES ('AAA', 'PIPPO', '123456');
INSERT INTO CUSTOMERS (CustomerID, ContactName, Phone) VALUES ('BBB', 'PLUTO', '323456');
INSERT INTO CUSTOMERS (CustomerID, ContactName, Phone) VALUES ('CCC', 'PAPERINO', '723456');

CREATE SEQUENCE LIGHTS_DATA_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE
    ;
GO

CREATE TABLE LIGHTS_DATA
(
    ID bigint PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR dbo.LIGHTS_DATA_ID),
    MAC_ADDRESS nvarchar(64) NOT NULL,
    LIGHT_VALUE int NOT NULL,
    capture_time DATETIME NOT NULL
);

-- INSERT INTO LIGHTS_DATA (MAC_ADDRESS, LIGHT_VALUE, capture_time) VALUES ('PIPPO', 1, CURRENT_TIMESTAMP)

CREATE TABLE LIGHTS_DATA_UNIQUE
(
    ID bigint PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR dbo.LIGHTS_DATA_ID),
    MAC_ADDRESS nvarchar(64) NOT NULL UNIQUE,
    LIGHT_VALUE int NOT NULL,
    capture_time DATETIME NOT NULL
);

